arch = [
    "base",
    "base-devel",
    "bash-completion",
    "bc",
    "flatpak-xdg-utils",
    "git",
    "hub",
    "inetutils",
    "lsof",
    "man-db",
    "man-pages",
    "mesa",
    "metapac-bin",
    "mtr",
    "nss-mdns",
    "openssh",
    "paru-bin",
    "pigz",
    "plocate",
    "rsync",
    "tcpdump",
    "time",
    "topgrade-bin",
    "traceroute",
    "tree",
    "unzip",
    "vte-common",
    "vulkan-intel",
    "vulkan-radeon",
    "wget",
    "words",
    "zip"
]
